### ISSUE TITLE
centroid calc

### ISSUE THREAD

**Issue by missinglink** [paulmach/go.geo#23]
hey @paulmach I've been playing with an alternate irregular polygon centroid algorithm which I borrowed from https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L404 

in theory it should provide a better 'center of gravity' calc than than the existing `PointSet.Centroid()` algo as it converts the coords to a spherical coordinate space before averaging the values.

what are your thoughts? is this something you'd be interested in merging at some point?

see: http://geojson.io/#id=gist:anonymous/ecd1ce4af92368aa4aea&map=3/-72.39/167.70

```go
package main

import "fmt"
import "math"
import "github.com/paulmach/go.geo"

func main() {
  // berlin := geo.NewPoint(13.408056,52.518611)
  // moscow := geo.NewPoint(37.617778,55.751667)
  // points := geo.PointSet{}
  // points.Push(berlin).Push(moscow)

  // rough new zealand polygon
  // ref: http://geojson.io/#id=gist:anonymous/adc4993b4b85f55ea9ae
  // points := geo.PointSet{}
  // points.Push(geo.NewPoint(172.1298828125,-33.97980872872456))
  // points.Push(geo.NewPoint(172.1298828125,-37.30027528134431))
  // points.Push(geo.NewPoint(165.8974609375,-38.54816542304658))
  // points.Push(geo.NewPoint(168.1728515625,-46.10370875598026))
  // points.Push(geo.NewPoint(179.7802734375,-47.8721439688873))
  // // points.Push(geo.NewPoint(-188.1298828125,-33.97980872872456))

  // antarctica bbox
  points := geo.PointSet{}
  points.Push(geo.NewPoint(148.7109375,-84.83422451455142))
  points.Push(geo.NewPoint(148.7109375,-76.51681887717322))
  points.Push(geo.NewPoint(186.6796875,-76.51681887717322))
  points.Push(geo.NewPoint(186.6796875,-84.83422451455142))

  fmt.Println(points)
  fmt.Println(points.Centroid())
  fmt.Println(getCentroid(points))
}

func getCentroid(ps geo.PointSet) *geo.Point {

  X := 0.0
  Y := 0.0
  Z := 0.0

  var toRad = math.Pi / 180
  var fromRad = 180 / math.Pi

  for _, point := range ps {

    var lon = point[0] * toRad
    var lat = point[1] * toRad

    X += math.Cos(lat) * math.Cos(lon)
    Y += math.Cos(lat) * math.Sin(lon)
    Z += math.Sin(lat)
  }

  numPoints := float64(len(ps))
  X = X / numPoints
  Y = Y / numPoints
  Z = Z / numPoints

  var lon = math.Atan2(Y, X)
  var hyp = math.Sqrt(X * X + Y * Y)
  var lat = math.Atan2(Z, hyp)

  var centroid = geo.NewPoint(lon * fromRad, lat * fromRad)

  return centroid;
}
```

**Comment by paulmach** [comment]
Hi Peter, sorry for the late reply. I've been out of town and off grid for the last 3 weeks.  

I think this is a great implementation for a center of a geo pointset. The naming convention used here is Centroid() would be for Cartesian points, or those projected to a conformal projection, and GeoCentroid() would work on latlng points. An example of this is point.DistanceFrom and point.GeoDistanceFrom. 

Are you interested in implementing this or do you want me to go ahead and add it?

**Comment by missinglink** [comment]
hey @paulmach I'm pretty new to Go, so probably best if you do it so I don't mess up your code ;)

**Comment by paulmach** [comment]
Okay, I'll add it to my todo list.

Are you guys using this library at mapzen?

**Comment by missinglink** [comment]
I'd like to start using it more for https://github.com/pelias/pbf2json

**Comment by paulmach** [comment]
Very cool.  Merged the `GeoCentroid`  https://github.com/paulmach/go.geo/commit/c84b6002b0f727d4a2d40e05466dfc3cc54eb329
