### ISSUE TITLE
MySQL scanning POLYGON WKB Always results in EMPTY

### ISSUE THREAD

**Issue by faxal** [paulmach/go.geo#33]
For example I used this and scanned it to a `geo.PointSet`

    SET @g = 'POLYGON((50.866753 5.686455, 50.859819 5.708942, 50.851475 5.722675, 50.841611 5.720615, 50.834023 5.708427, 50.840744 5.689373, 50.858735 5.673923, 50.866753 5.686455))';
    SELECT ST_AsBinary(PolyFromText(@g));
    
---
    var p *geo.PointSet
    row.Scan(&p)

    // 	p == EMPTY

It's very likely that I'm way  off on this. What am I doing wrong?

**Comment by faxal** [comment]
I dug a little deeper, it seems `PointSet` is just `[]Point`. So library doesn't actually support `POLYGON` or else there has to be some type with `[][]Point`. I don't know if this was intentional or not.

[#L221-L223](https://github.com/paulmach/go.geo/blob/c0ac1efaa83d0fd366386e188ab59ff70ecb0b31/wkb.go#L221-L223) looks like it wants to support `POLYGON` but then (#L225)[https://github.com/paulmach/go.geo/blob/e8994de4ca767ad1e416ce5e185f83538f0661a8/wkb.go#L225] will fail with `POLYGON` WKB because what follows is number of rings not number of points.

I think this is the most complete library for handling Geo-spatial data in Go and it would be nice to have `POLYGON` support, specially WKB support as it will make working with databases a breeze.

**Comment by paulmach** [comment]
Yes, did the same digging :)   Here is the fix https://github.com/paulmach/go.geo/pull/34

**Comment by faxal** [comment]
Nice! :+1: Thanks!. Fortunately I don't need multi ring support.

**Comment by twpayne** [comment]
@paulmach, if you want a load of WKB test data covering many geometry types, feel free to copy it from https://github.com/twpayne/go-geom/blob/master/encoding/wkb/wkb_test.go and https://github.com/twpayne/go-geom/blob/master/internal/testdata/random.go.

**Comment by paulmach** [comment]
I think this is fixed, but there is more work to do. Thank @twpayne I'll look into adding more tests.
