### ISSUE TITLE
Marshal to GeoJSON by default

### ISSUE THREAD

**Issue by derekperkins** [paulmach/go.geo#37]
Rather than having to use `ToGeoJSON()`, is there a reason not to just have a built in custom `MarshalJSON()` that defaults to GeoJSON? That would allow embedded geo fields to marshal properly to GeoJSON out of the box.

**Comment by ARolek** [comment]
Though I'm not a contributor to this package, this does seem logical. It would be a braking change to the API to remove `ToGeoJSON()` method, but the structs would then comply with the `json.Marshaler` interface. If implemented, the `UnmarshalJSON([]byte) error` method should also be considered for addition.

**Comment by derekperkins** [comment]
You could still leave `ToGeoJSON()` as a part of the package.

**Comment by paulmach** [comment]
A couple questions. One I usually find my self using the package as:
```
type Something struct {
  ID int
  Name string
  Location *geo.Point
}
```
For my use cases I want this to marshal to something like `{"id":1,"name":"a","location":[1.0, 2.0]}`. But I guess I'm not against that being geojson.

The other question is geojson feature or geometry? Currently `ToGeoJSON` outputs a feature, is that correct?

**Comment by ARolek** [comment]
I seems to make sense to follow the [GeoJSON spec](http://geojson.org/geojson-spec.html). In your example struct, the output would be formatted as follows:

```json
{
	"id": 1,
	"name": "a",
	"location": {
		"type": "Point",
		"coordinates": [
			1.0, 2.0
		],
		"crs": {
			"type": "name",
			"properties": {
				"name": "...projection identifier..."
			}
		}
	}
}
```

I have found the `crs` parameter to be critical when inserting data into PostGIS using the `ST_GeomFromGeoJson` function. Without the `crs` a consumer will not know for sure what projection the geojson data uses.

**Comment by paulmach** [comment]
This library, at least in my mind, is a light weight geo manipulation library. I'm kind of leaving projection stuff out of the data, it's up to the user to know what projection stuff is in. 

To get MarshalJSON to output geoJSON, one option is to create a package variable like `MarshalToGeoJSON`  that if set to true would change the behavior of MarshalJSON.  Not really the best solution but could work.

Alternately you may look at https://github.com/twpayne/go-geom/  I haven't look super closely but I think it would support some of the projection information way better.

**Comment by derekperkins** [comment]
The fact that you implement `sql.Scanner` and `sql.Valuer` makes this the library of choice for me. If there is anything in other libraries, I'm sure we could port some of it over here. 

Not having MarshalJSON supported by default means that any nested fields don't marshal to GeoJSON properly. I think adding a variable to enable/disable GeoJSON marshaling by default sounds good for now.

**Comment by paulmach** [comment]
okay, what about not having crs, is that an issue for you?

**Comment by ARolek** [comment]
Interesting discussion. Sorry to keep chiming in but I'm quite interested in the development of GIS packages in Go. 

A variable toggle in the package to modify the output of `MarshalJSON()` smells a bit strange to me. I think you should pick a convention and stick with it.

Regarding the `crs` output included in the GeoJSON payload I do think this would be valuable. According to your documentation the library supports:

- Project between WGS84 (EPSG:4326) and Mercator (EPSG:3857) or Scalar Mercator (map tiles)

It seems to make sense to include the CRS in the output as you support more than one. Ultimately the `crs` property could be added at a later date as it would not break the data contract, only enhance it.

Just my 2 cents. Thanks for the great work.

**Comment by paulmach** [comment]
I know this is super old, but closing it for completeness :)

There are several issues brought up here:

> is there a reason not to just have a built in custom MarshalJSON() that defaults to GeoJSON

Because sometimes you want a point to marshal as `[10, 20]` and other times to GeoJSON. To do this today I'd recommend using [orb/geojson](https://github.com/paulmach/orb/tree/master/geojson) and using the types there. For example:
```
type Something struct {
  ID int
  Name string
  Location geojson.Point
}
```
would marshal/unmarshal the `Location` and a geojson geometry object. This isn't the same as making it the default, but I think it's workable.  It would possible to add support for Scanning from WKB into a `geojson.Point` to [encoding/wkb](https://github.com/paulmach/orb/tree/master/encoding/wkb) if there is interest.

> crs

Coordinate Reference System have been removed from the most recent [geojson spec](https://tools.ietf.org/html/rfc7946#section-4). Also, some of the types in this library, as currently defined, don't support extra info/properties. So this isn't possible without a major change.
