### ISSUE TITLE
compute center of a path

### ISSUE THREAD

**Issue by missinglink** [paulmach/go.geo#42]
heya, is it currently possible to compute the mid point along a path (a point on the line string which is exactly 50% along the line)?

I had a look at the APIs and I guess I could use `path.Distance()` to get the total distance, then I think I would need to walk the points to find the line segment which lies in the center, from there it's a task of interpolating along that segment to find the correct position.

is this all possible with the existing methods or would it require me to open a PR to add additional methods?

**Comment by missinglink** [comment]
This seems to work for me?

```
// GetLineCentroid - compute the centroid of a line string
func GetLineCentroid(ps *geo.PointSet) *geo.Point {

	path := geo.NewPath()
	path.PointSet = *ps

	halfDistance := path.Distance() / 2
	travelled := 0.0

	for i := 0; i < len(path.PointSet)-1; i++ {

		segment := geo.NewLine(&path.PointSet[i], &path.PointSet[i+1])
		distance := segment.Distance()

		// middle line segment
		if (travelled + distance) > halfDistance {
			var remainder = halfDistance - travelled
			return segment.Interpolate(remainder / distance)
		}

		travelled += distance
	}

	return ps.GeoCentroid()
}
```

**Comment by missinglink** [comment]
would you accept a PR for this? I was thinking of calling it `path.Centroid()` to keep with the exiting method names.

**Comment by missinglink** [comment]
![rail](https://cloud.githubusercontent.com/assets/738069/17410796/92af9200-5a75-11e6-843b-6e502cc8c4c6.png)

**Comment by paulmach** [comment]
I think a `path.Interpolate(v)` method would be great. That would match the `line.Interpolate(v)` method well.

I think you can get what you what right now using `path.Resample(3).Get(1)`  but that's not very clear.

**Comment by missinglink** [comment]
I tried the resample method but the point it returns is not on the original line string.

I'll open a PR

**Comment by paulmach** [comment]
weird, can you share the example line string?

**Comment by missinglink** [comment]
https://github.com/pelias/pbf2json/blob/line_centroid/line_centroid_test.go

**Comment by missinglink** [comment]
hmm.. ok weird you're right, I might have screwed that up

**Comment by missinglink** [comment]
I can PR the `line.Interpolate(v)` anyway since it's useful
