### ISSUE TITLE
Adding identifer column to Point object for quad tree investigation

### ISSUE THREAD

**Issue by jvalentine** [paulmach/go.geo#46]
Hi, not an issue so much, as something I'm struggling with adapting. 

I need the ability to have a number associated with a geo point, in order to reference back to what it relates to. I've customised the point type to have length of 3 instead of 2, with the 3rd float been the ID, so the idea was, when I ran a nearest command against the quad tree of points, I'd be able to find it's owner. 

The creating of the point works, and the existing tests pass. But soon as the point is added to the quad tree, it appears to lose it's 3rd value, returning X and Y as expected, but the 3rd number is always 0. 

Is there something I'm missing in the quad tree section, that is removing this 3rd column. Any help or advice on the best way to approach this would be much appreciated!

**Comment by paulmach** [comment]
hum, I was unable to duplicate this, let me know if I am doing something wrong or if there is other code I could help debug.

I changed [2]float64 -> [3]float64 then ran:
```
r := rand.New(rand.NewSource(42)) // to make things reproducible
qt := quadtree.New(geo.NewBound(0, 1, 0, 1))

// insert 1000 random points
for i := 0; i < 1000; i++ {
	p := geo.NewPoint(r.Float64(), r.Float64())
	p[2] = 123
	qt.Insert(p)
}

nearest := qt.Find(geo.NewPoint(0.5, 0.5))
fmt.Printf("nearest: %+v %v\n", nearest, nearest.Point()[2])

// Output:
// nearest: POINT(0.4930591659434973 0.5196585530161364) 123
```

If you want to do it without modifying the library you can implement the pointer interface, like:
```
type OtherType struct {
	Loc *geo.Point
	ID  int
}

func (ot OtherType) Point() *geo.Point {
	return ot.Loc
}

ot := &OtherType{geo.NewPoint(r.Float64(), r.Float64()), 123}
qt.Insert(ot)

nearest := qt.Find(geo.NewPoint(0.5, 0.5))
ot2 := nearest.(*OtherType)
```

Sadly I just realized that the `Pointer interface{ Point() *geo.Point }` interface makes it so you can't just embed the `*geo.Point`

**Comment by jvalentine** [comment]
Thanks Paul, after seeing your code work, I found the issue was with the way I was referencing it, Thanks for getting back so quickly Paul, it's a very useful package!

**Comment by paulmach** [comment]
cool, glad it works.

**Comment by abonec** [comment]
In my situation I have the path and put it to the quadtree for search and comparing with reference path by _bearing_. For calculate _bearing_ I need index of point in a path.

I see it is common problem to get index of point. It is possible to add index field to point in library and may be fill it up with the index from path if it comes from? Or set index by hand in some other situations.

It will be handy instead of construct custom pointers and much simpler for newbie in golang like me.
