### ISSUE TITLE
Support MultiPolygon type when reading the WKB data from db

### ISSUE THREAD

**Issue by januszm** [paulmach/go.geo#61]
I'd like to be able to scan data from the `multipolygon` column from the PostGIS database into Go app.

I was hoping I could simply define a struct where one of the fields is of type `MultiPolygon`:

```golang
import(geo "github.com/paulmach/go.geo")
...
type Area struct {
	ID        uuid.UUID        `gorm:"column:id" json:"id"`
	Shape     *geo.MultiPolygon `gorm:"column:shape" json:"shape"`
```

However, of course such a type is not yet defined. 

Is there a way to actually read the MultiPolygon data from PostGIS?

Also it seems that we have to run the `ST_AsBinary` function when fetching data from the database. Failing to do so results in the `sql: Scan error on column index 3: go.geo: invalid WKB data` error. 

Couldn't we always apply the `ST_AsBinary` function? eg. when defining the struct? I'd say that the typical scenario is that the data is actually saved as WKB binary and the ST_AsBinary function simply changes:

```
shape | 01060...E614340
```
to
```
st_asbinary | \x01060...e614340
```

**Comment by januszm** [comment]
Just a note, maybe I'm totally wrong and I should use a different go package? What I want to do later with this data is to render JSON response, so I might just need to read the WKB data and convert to GeoJSON MultiPolygon data.

**Comment by paulmach** [comment]
This library does not have a MultiPolygon type. Given the current types and how things are setup I'm kind of against adding such a type.

Over the last while I've been working on a new library that has a nicer API. Depending on how "production" you need your code you may consider using [orb](https://github.com/paulmach/orb). It does almost everything this library does, just at tad differently (I think better).

**Comment by januszm** [comment]
Thanks @paulmach I'll give orb a try, I'll close this issue.
