### ISSUE TITLE
ST_AsBinary return result of 44 length hex

### ISSUE THREAD

**Issue by mwei0210** [paulmach/go.geo#66]
By following the example, it returned "\x010100000000000000000024c00000000000003e40" to go.geo causing "go.geo: incorrect geometry" error

Any idea what's wrong? thanks!

**Comment by mwei0210** [comment]
I have 'SELECT ST_AsBinary(coordinate) FROM table'

Does it mean i have to convert it again before passing to it?

**Comment by paulmach** [comment]
if you are Scanning it into a []byte and the resulting slice is 44 bytes then it's something to do with sql driver settings.

if it's 21 bytes then there is something else wrong

**Comment by mwei0210** [comment]
I guess you are right about 42hex chars to 21 bytes. What could i do to receive 21 bytes so it could scan into Point? I am using it with (go-pg) [https://godoc.org/github.com/go-pg/pg#DB.Query] if it matters

**Comment by paulmach** [comment]
does it work if you use https://github.com/lib/pq directly?

**Comment by mwei0210** [comment]
Yeah i think it did work when i was briefly  testing with https://github.com/lib/pq

**Comment by mwei0210** [comment]
length of 44 is after `data, ok := value.([]byte)` conversion
at [here](https://github.com/paulmach/go.geo/blob/master/wkb.go#L75)

**Comment by mwei0210** [comment]
tried doing `hex.DecodeString(string(data))` after `data, ok := value.([]byte)` and it worked, but couldnt find the equivalent in postgres that does that

**Comment by paulmach** [comment]
looks like this was fixed in may by https://github.com/paulmach/go.geo/pull/67
